/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ControladorMascota;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Mascota;


public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    
    private enum TipoBusqueda
    {
        Nombre,
        Tipo
    }
    
    private TipoBusqueda tipoBusqueda = TipoBusqueda.Nombre;
    
    
    public Ventana() 
    {
        initComponents();
        //BLOQUEAR LOS PANELES
        pnl_almacenar.setVisible(false);
        pnl_buscar.setVisible(false);
        pnl_listar.setVisible(false);
        pnl_modificar.setVisible(false);
        
        //BLOQUEAR LOS CHECKLIST  
        txt_cantidad.setEnabled(false);
        txt_duenho.setEnabled(false);
        
        setTitle("MEDIPED");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btt_buscar = new javax.swing.ButtonGroup();
        pnl_almacenar = new javax.swing.JPanel();
        lbl_1 = new javax.swing.JLabel();
        lbl_2 = new javax.swing.JLabel();
        txt_nombre = new javax.swing.JTextField();
        txt_edad = new javax.swing.JTextField();
        lbl_4 = new javax.swing.JLabel();
        cmb_tipo = new javax.swing.JComboBox<>();
        lbl_5 = new javax.swing.JLabel();
        chk_atencion = new javax.swing.JCheckBox();
        lbl_6 = new javax.swing.JLabel();
        txt_cantidad = new javax.swing.JTextField();
        chk_duenho = new javax.swing.JCheckBox();
        lbl_7 = new javax.swing.JLabel();
        txt_duenho = new javax.swing.JTextField();
        lbl_8 = new javax.swing.JLabel();
        txt_descripcion = new javax.swing.JTextField();
        btn_limpiar = new javax.swing.JButton();
        btn_almacenar = new javax.swing.JButton();
        pnl_buscar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tbl_lista = new javax.swing.JScrollPane();
        tbl_mascotas = new javax.swing.JTable();
        rbt_nombre = new javax.swing.JRadioButton();
        rbt_tipo = new javax.swing.JRadioButton();
        txt_buscar = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_modificarPanel = new javax.swing.JButton();
        lbl_9 = new javax.swing.JLabel();
        cmb_tipoBuscar = new javax.swing.JComboBox<>();
        pnl_listar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        tbl_lista1 = new javax.swing.JScrollPane();
        tbl_listamascota = new javax.swing.JTable();
        btn_listar = new javax.swing.JButton();
        pnl_modificar = new javax.swing.JPanel();
        lbl_3 = new javax.swing.JLabel();
        lbl_10 = new javax.swing.JLabel();
        txt_nombreMod = new javax.swing.JTextField();
        txt_edadMod = new javax.swing.JTextField();
        lbl_11 = new javax.swing.JLabel();
        cmb_tipoMod = new javax.swing.JComboBox<>();
        lbl_12 = new javax.swing.JLabel();
        chk_atencionMod = new javax.swing.JCheckBox();
        lbl_13 = new javax.swing.JLabel();
        txt_cantidadMod = new javax.swing.JTextField();
        chk_duenhoMod = new javax.swing.JCheckBox();
        lbl_14 = new javax.swing.JLabel();
        txt_duenhoMod = new javax.swing.JTextField();
        lbl_15 = new javax.swing.JLabel();
        txt_descripcionMod = new javax.swing.JTextField();
        btn_limpiar1 = new javax.swing.JButton();
        btn_modificar = new javax.swing.JButton();
        txt_idMod = new javax.swing.JTextField();
        lbl_17 = new javax.swing.JLabel();
        lbl_18 = new javax.swing.JLabel();
        mnb_1 = new javax.swing.JMenuBar();
        men_opcion = new javax.swing.JMenu();
        mi_almacenar = new javax.swing.JMenuItem();
        mi_buscar = new javax.swing.JMenuItem();
        mi_listar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_1.setText("NOMBRE:");

        lbl_2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_2.setText("NUEVA MASCOTA");

        txt_nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_nombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nombreFocusLost(evt);
            }
        });
        txt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreActionPerformed(evt);
            }
        });
        txt_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreKeyReleased(evt);
            }
        });

        txt_edad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_edad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_edadFocusLost(evt);
            }
        });
        txt_edad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadActionPerformed(evt);
            }
        });

        lbl_4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_4.setText("TIPO:");

        cmb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "PERRO", "GATO", "TORTUGA", "TIGRE", "PINGUINO", " " }));
        cmb_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoActionPerformed(evt);
            }
        });

        lbl_5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_5.setText("EDAD:");

        chk_atencion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chk_atencion.setText("¿POSEE ATENCIONES PREVIAS?");
        chk_atencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_atencionActionPerformed(evt);
            }
        });

        lbl_6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_6.setText("CANTIDAD:");

        txt_cantidad.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_cantidad.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadFocusLost(evt);
            }
        });
        txt_cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadActionPerformed(evt);
            }
        });

        chk_duenho.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chk_duenho.setText("¿POSEE DUEÑO?");
        chk_duenho.setToolTipText("");
        chk_duenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_duenhoActionPerformed(evt);
            }
        });

        lbl_7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_7.setText("NOMBRE DEL DUEÑO:");

        txt_duenho.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_duenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_duenhoActionPerformed(evt);
            }
        });
        txt_duenho.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_duenhoKeyReleased(evt);
            }
        });

        lbl_8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_8.setText("DESCRIPCIÓN:");

        txt_descripcion.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txt_descripcion.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_descripcion.setToolTipText("");
        txt_descripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionActionPerformed(evt);
            }
        });
        txt_descripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionKeyReleased(evt);
            }
        });

        btn_limpiar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_limpiar.setText("LIMPIAR");
        btn_limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiarActionPerformed(evt);
            }
        });

        btn_almacenar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_almacenar.setText("ALMACENAR");
        btn_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_almacenarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_almacenarLayout = new javax.swing.GroupLayout(pnl_almacenar);
        pnl_almacenar.setLayout(pnl_almacenarLayout);
        pnl_almacenarLayout.setHorizontalGroup(
            pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                        .addGap(0, 70, Short.MAX_VALUE)
                        .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                .addComponent(chk_duenho)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_duenho, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbl_8)
                            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                        .addComponent(lbl_4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(88, 88, 88)
                                        .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                                .addComponent(lbl_6)
                                                .addGap(18, 18, 18)
                                                .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(chk_atencion)))
                                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                        .addComponent(lbl_1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(113, 113, 113)
                                        .addComponent(lbl_5)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap(11, Short.MAX_VALUE))
                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                        .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_descripcion)
                            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                                .addComponent(btn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                .addGap(206, 206, 206)
                .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_almacenarLayout.setVerticalGroup(
            pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_almacenarLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_nombre)
                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbl_1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cmb_tipo))
                        .addGap(64, 64, 64))
                    .addGroup(pnl_almacenarLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(chk_atencion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_duenho)
                    .addComponent(lbl_7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(chk_duenho, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lbl_8, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_almacenarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_almacenar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("BUSQUEDA DE MASCOTAS");

        tbl_mascotas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_mascota", "nombre_mascota", "Edad", "tipo_mascota", "check_duenho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_lista.setViewportView(tbl_mascotas);

        btt_buscar.add(rbt_nombre);
        rbt_nombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_nombre.setSelected(true);
        rbt_nombre.setText("BUSCAR POR NOMBRE");
        rbt_nombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_nombreActionPerformed(evt);
            }
        });

        btt_buscar.add(rbt_tipo);
        rbt_tipo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbt_tipo.setText("BUSCAR POR TIPO");
        rbt_tipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbt_tipoActionPerformed(evt);
            }
        });

        txt_buscar.setBorder(null);
        txt_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_buscarActionPerformed(evt);
            }
        });
        txt_buscar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_buscarKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("NOMBRE:");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        btn_buscar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_buscar.setText("BUSCAR");
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        btn_eliminar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_eliminar.setText("ELIMINAR");
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_modificarPanel.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_modificarPanel.setText("MODIFICAR");
        btn_modificarPanel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarPanelActionPerformed(evt);
            }
        });

        lbl_9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_9.setText("TIPO:");

        cmb_tipoBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "PERRO", "GATO", "TORTUGA", "TIGRE", "PINGUINO", " " }));
        cmb_tipoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_buscarLayout = new javax.swing.GroupLayout(pnl_buscar);
        pnl_buscar.setLayout(pnl_buscarLayout);
        pnl_buscarLayout.setHorizontalGroup(
            pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buscarLayout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(rbt_nombre)
                .addGap(111, 111, 111)
                .addComponent(rbt_tipo)
                .addGap(117, 117, 117))
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(btn_eliminar)
                .addGap(136, 136, 136)
                .addComponent(btn_modificarPanel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(lbl_9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmb_tipoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_buscarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbl_lista)
                .addGap(23, 23, 23))
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addGap(285, 285, 285)
                .addComponent(btn_buscar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_buscarLayout.setVerticalGroup(
            pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_buscarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbt_nombre)
                    .addComponent(rbt_tipo))
                .addGap(18, 18, 18)
                .addGroup(pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_tipoBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_buscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tbl_lista, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnl_buscarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificarPanel)
                    .addComponent(btn_eliminar))
                .addContainerGap(490, Short.MAX_VALUE))
        );

        txt_buscar.getAccessibleContext().setAccessibleName("");
        txt_buscar.getAccessibleContext().setAccessibleParent(rbt_nombre);
        jLabel2.getAccessibleContext().setAccessibleName("");
        jLabel2.getAccessibleContext().setAccessibleParent(rbt_nombre);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel3.setText("LISTA DE MASCOTAS");

        tbl_listamascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id_mascota", "nombre_mascota", "Edad", "tipo_mascota", "check_duenho"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_lista1.setViewportView(tbl_listamascota);

        btn_listar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btn_listar.setText("LISTAR");
        btn_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_listarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_listarLayout = new javax.swing.GroupLayout(pnl_listar);
        pnl_listar.setLayout(pnl_listarLayout);
        pnl_listarLayout.setHorizontalGroup(
            pnl_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_listarLayout.createSequentialGroup()
                        .addComponent(tbl_lista1)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_listarLayout.createSequentialGroup()
                        .addGap(0, 214, Short.MAX_VALUE)
                        .addGroup(pnl_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_listarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(216, 216, 216))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_listarLayout.createSequentialGroup()
                                .addComponent(btn_listar)
                                .addGap(271, 271, 271))))))
        );
        pnl_listarLayout.setVerticalGroup(
            pnl_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_listar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tbl_lista1, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        pnl_modificar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                pnl_modificarKeyReleased(evt);
            }
        });

        lbl_3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_3.setText("NOMBRE:");

        lbl_10.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_10.setText("MODIFICAR MASCOTA");

        txt_nombreMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_nombreMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nombreModFocusLost(evt);
            }
        });
        txt_nombreMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nombreModActionPerformed(evt);
            }
        });
        txt_nombreMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_nombreModKeyReleased(evt);
            }
        });

        txt_edadMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_edadMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_edadModFocusLost(evt);
            }
        });
        txt_edadMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_edadModActionPerformed(evt);
            }
        });

        lbl_11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_11.setText("TIPO:");

        cmb_tipoMod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--SELECCIONE--", "PERRO", "GATO", "TORTUGA", "TIGRE", "PINGUINO", " " }));
        cmb_tipoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoModActionPerformed(evt);
            }
        });

        lbl_12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_12.setText("EDAD:");

        chk_atencionMod.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chk_atencionMod.setText("¿POSEE ATENCIONES PREVIAS?");
        chk_atencionMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_atencionModActionPerformed(evt);
            }
        });

        lbl_13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_13.setText("ID MASCOTA:");

        txt_cantidadMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_cantidadMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_cantidadModFocusLost(evt);
            }
        });
        txt_cantidadMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_cantidadModActionPerformed(evt);
            }
        });

        chk_duenhoMod.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        chk_duenhoMod.setText("¿POSEE DUEÑO?");
        chk_duenhoMod.setToolTipText("");
        chk_duenhoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chk_duenhoModActionPerformed(evt);
            }
        });

        lbl_14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_14.setText("NOMBRE DEL DUEÑO:");

        txt_duenhoMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_duenhoMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_duenhoModActionPerformed(evt);
            }
        });
        txt_duenhoMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_duenhoModKeyReleased(evt);
            }
        });

        lbl_15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_15.setText("DESCRIPCIÓN:");

        txt_descripcionMod.setFont(new java.awt.Font("Garamond", 1, 18)); // NOI18N
        txt_descripcionMod.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        txt_descripcionMod.setToolTipText("");
        txt_descripcionMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripcionModActionPerformed(evt);
            }
        });
        txt_descripcionMod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_descripcionModKeyReleased(evt);
            }
        });

        btn_limpiar1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_limpiar1.setText("LIMPIAR");
        btn_limpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limpiar1ActionPerformed(evt);
            }
        });

        btn_modificar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_modificar.setText("MODIFICAR");
        btn_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_modificarActionPerformed(evt);
            }
        });

        txt_idMod.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txt_idMod.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_idModFocusLost(evt);
            }
        });
        txt_idMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idModActionPerformed(evt);
            }
        });

        lbl_17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_17.setText("CANTIDAD:");

        lbl_18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lbl_18.setText("CAMPOS A MODIFICAR");

        javax.swing.GroupLayout pnl_modificarLayout = new javax.swing.GroupLayout(pnl_modificar);
        pnl_modificar.setLayout(pnl_modificarLayout);
        pnl_modificarLayout.setHorizontalGroup(
            pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_modificarLayout.createSequentialGroup()
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modificarLayout.createSequentialGroup()
                                .addComponent(lbl_17)
                                .addGap(18, 18, 18)
                                .addComponent(txt_cantidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(130, 130, 130))
                            .addComponent(chk_atencionMod, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(21, 21, 21))
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_descripcionMod)
                            .addGroup(pnl_modificarLayout.createSequentialGroup()
                                .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_limpiar1, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(pnl_modificarLayout.createSequentialGroup()
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnl_modificarLayout.createSequentialGroup()
                                .addComponent(chk_duenhoMod)
                                .addGap(18, 18, 18)
                                .addComponent(lbl_14)
                                .addGap(18, 18, 18)
                                .addComponent(txt_duenhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl_modificarLayout.createSequentialGroup()
                                .addComponent(lbl_11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                                        .addComponent(lbl_3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_nombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(52, 52, 52)
                                        .addComponent(lbl_12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_edadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cmb_tipoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbl_15)))
                .addGap(0, 54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_modificarLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(lbl_13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_idMod, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54))
                    .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lbl_18)
                        .addComponent(lbl_10)))
                .addGap(219, 219, 219))
        );
        pnl_modificarLayout.setVerticalGroup(
            pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_modificarLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addComponent(lbl_10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl_13, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_modificarLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(txt_idMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addComponent(lbl_18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_edadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_nombreMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chk_atencionMod)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmb_tipoMod)
                    .addComponent(txt_cantidadMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_17, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chk_duenhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txt_duenhoMod, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addComponent(lbl_15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_descripcionMod, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_modificarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_modificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_limpiar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        men_opcion.setText("Opciones");

        mi_almacenar.setText("Almacenar Mascota");
        mi_almacenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_almacenarActionPerformed(evt);
            }
        });
        men_opcion.add(mi_almacenar);

        mi_buscar.setText("Buscar/Eliminar Mascota");
        mi_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_buscarActionPerformed(evt);
            }
        });
        men_opcion.add(mi_buscar);

        mi_listar.setText("Listar Mascota");
        mi_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_listarActionPerformed(evt);
            }
        });
        men_opcion.add(mi_listar);

        mnb_1.add(men_opcion);

        jMenu2.setText("Quienes Somos");
        mnb_1.add(jMenu2);

        setJMenuBar(mnb_1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnl_almacenar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_almacenar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_modificar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnl_listar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(496, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mi_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_almacenarActionPerformed
        pnl_almacenar.setVisible(true);
        pnl_listar.setVisible(false);
        pnl_buscar.setVisible(false);
        pnl_modificar.setVisible(false);
        setTitle("MEDIPED - ALMACENAR MASCOTA");
       
        
    }//GEN-LAST:event_mi_almacenarActionPerformed

    private void mi_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_buscarActionPerformed
        pnl_buscar.setVisible(true);
        pnl_listar.setVisible(false);
        pnl_almacenar.setVisible(false);
        pnl_modificar.setVisible(false);
        setTitle("MEDIPED - BUSCAR MASCOTA");
        cmb_tipoBuscar.setEnabled(false);
        
        
        
    }//GEN-LAST:event_mi_buscarActionPerformed

    private void mi_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_listarActionPerformed
        // BOTON LISTAR MASCOTAS
        
        pnl_listar.setVisible(true);
        pnl_buscar.setVisible(false);
        pnl_almacenar.setVisible(false);
        pnl_modificar.setVisible(false);
        setTitle("MEDIPED - LISTAR MASCOTA");
    }//GEN-LAST:event_mi_listarActionPerformed

    private void txt_cantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_txt_cantidadActionPerformed

    private void cmb_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoActionPerformed

    private void txt_edadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadActionPerformed

    private void txt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreActionPerformed

    private void txt_duenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_duenhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duenhoActionPerformed

    private void txt_descripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionActionPerformed

    private void btn_almacenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_almacenarActionPerformed
        boolean validadorReglas = validarReglasNegocio();
        
            if(validadorReglas)//VERIFICAR POSTERIORMENTE REGLAS DE NEGOCIO
           { //LLAVE QUE ABRE REGLAS DE NEGOCIO
            Mascota mascota = new Mascota();
            ControladorMascota ctrlMascota = new ControladorMascota();
            boolean validador = false;


            mascota.setNombreMascota(txt_nombre.getText());

            if(!txt_edad.getText().equals("")) mascota.setEdad(Integer.parseInt(txt_edad.getText()));

           mascota.setTipoMascota((String)cmb_tipo.getSelectedItem());

            if(chk_atencion.isSelected()){
                mascota.setAtenPrevias(true);
                mascota.setCantAtenPrevias(Integer.parseInt(txt_cantidad.getText()));
            }

            if(chk_duenho.isSelected()){
                mascota.setCheckDuenho(true);
                mascota.setNombreDuenho(txt_duenho.getText());
            }

            if(!txt_descripcion.getText().equals("")){
                mascota.setDescripcion(txt_descripcion.getText());
            }else{
                mascota.setDescripcion("Sin Descripcion");
            }

            validador = ctrlMascota.agregarMascota(mascota);



            if(validador)
                {
                    JOptionPane.showMessageDialog(rootPane, "MASCOTA ALMACENADA EXITOSAMENTE");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "ERROR AL ALMACENAR MASCOTA");
                }

                limpiarVentana();
                
            } //LLAVE QUE CIERRA REGLAS DE NEGOCIO
    }//GEN-LAST:event_btn_almacenarActionPerformed

    private void btn_limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiarActionPerformed
        // BOTON LIMPIAR
        
        limpiarVentana();
    }//GEN-LAST:event_btn_limpiarActionPerformed

    private void chk_atencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_atencionActionPerformed
        
        if(chk_atencion.isSelected())
        {
            txt_cantidad.setEnabled(true);
           
        }
        else
        {
            txt_cantidad.setEnabled(false);
            txt_cantidad.setText("");
            
        }
    }//GEN-LAST:event_chk_atencionActionPerformed

    private void chk_duenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_duenhoActionPerformed
        
        if(chk_duenho.isSelected())
        {
            txt_duenho.setEnabled(true);
            
            
            
            
        }
        else
        {
            txt_duenho.setEnabled(false);
            txt_duenho.setText("");
        }
    }//GEN-LAST:event_chk_duenhoActionPerformed

    private void txt_nombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreFocusLost
        String nombre = txt_nombre.getText();
        
        if(nombre.length() > 30)
        {
            JOptionPane.showMessageDialog(rootPane, "LONGITUD EXCEDE 30 CARACTERES");
            txt_nombre.setText("");
            txt_nombre.requestFocus();
        }
    }//GEN-LAST:event_txt_nombreFocusLost

    private void txt_edadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_edadFocusLost
        try
        {
            if(!txt_edad.getText().equals(""))
            {
                int edad = Integer.parseInt(txt_edad.getText());

                if(edad < 0 || edad > 150)
                {
                    JOptionPane.showMessageDialog(rootPane, "EDAD DEBE SER MAYOR A 0 Y MENOR A 150");
                    txt_edad.setText("");
                    txt_edad.requestFocus();
                }
            }
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "TIPO DE DATO DEBE SER ENTERO");
            txt_edad.setText("");
            txt_edad.requestFocus();
        }
    }//GEN-LAST:event_txt_edadFocusLost

    private void txt_nombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreKeyReleased
        String textoIngresado = txt_nombre.getText();
        int longitudIngresada = textoIngresado.length();
        
        if(longitudIngresada > 50)
        {
            txt_nombre.setText(textoIngresado.substring(0, 50));
        }
    }//GEN-LAST:event_txt_nombreKeyReleased

    private void txt_descripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionKeyReleased
        String textoIngresado = txt_descripcion.getText();
        int longitudIngresada = textoIngresado.length();
        
        if(longitudIngresada > 250)
        {
            txt_descripcion.setText(textoIngresado.substring(0, 250));
        }
    }//GEN-LAST:event_txt_descripcionKeyReleased

    private void txt_duenhoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_duenhoKeyReleased
        String textoIngresado = txt_nombre.getText();
        int longitudIngresada = textoIngresado.length();
        
        if(longitudIngresada > 50)
        {
            txt_nombre.setText(textoIngresado.substring(0, 50));
        }
    }//GEN-LAST:event_txt_duenhoKeyReleased

    private void btn_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_listarActionPerformed
        ArrayList<Mascota> listaMascotas = new ArrayList<>();
                  ControladorMascota ctrlMascota = new ControladorMascota();

                    listaMascotas = ctrlMascota.ListarMascotas();

                    DefaultTableModel ListarMascotas = 
                            (DefaultTableModel)tbl_listamascota.getModel();

                    ListarMascotas.setRowCount(0); //LIMPIA LA TABLA 

                    for(Mascota x: listaMascotas)
                    {
                        Object[] objs = {x.getIdMascota(), x.getNombreMascota(), x.getEdad()
                        ,x.getTipoMascota(),x.isCheckDuenho()};

                        ListarMascotas.addRow(objs);
                    }
    }//GEN-LAST:event_btn_listarActionPerformed

    private void txt_cantidadFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadFocusLost
        try
        {
            if(!txt_cantidad.getText().equals(""))
            {
                int edad = Integer.parseInt(txt_edad.getText());

                if(edad < 0 )
                {
                    JOptionPane.showMessageDialog(rootPane, "EDAD DEBE SER MAYOR A 0");
                    txt_cantidad.setText("");
                    txt_cantidad.requestFocus();
                }
            }
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "TIPO DE DATO DEBE SER ENTERO");
            txt_cantidad.setText("");
            txt_cantidad.requestFocus();
        }
    }//GEN-LAST:event_txt_cantidadFocusLost

    private void txt_nombreModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nombreModFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nombreModFocusLost

    private void txt_nombreModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nombreModActionPerformed
        String nombre = txt_nombreMod.getText();
        
        if(nombre.length() > 30)
        {
            JOptionPane.showMessageDialog(rootPane, "LONGITUD EXCEDE 30 CARACTERES");
            txt_nombreMod.setText("");
            txt_nombreMod.requestFocus();
        }
    }//GEN-LAST:event_txt_nombreModActionPerformed

    private void txt_nombreModKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_nombreModKeyReleased
        String textoIngresado = txt_nombreMod.getText();
        int longitudIngresada = textoIngresado.length();
        
        if(longitudIngresada > 50)
        {
            txt_nombreMod.setText(textoIngresado.substring(0, 50));
        }
    }//GEN-LAST:event_txt_nombreModKeyReleased

    private void txt_edadModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_edadModFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_edadModFocusLost

    private void txt_edadModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_edadModActionPerformed
        try
        {
            if(!txt_edadMod.getText().equals(""))
            {
                int edad = Integer.parseInt(txt_edadMod.getText());

                if(edad < 0 || edad > 150)
                {
                    JOptionPane.showMessageDialog(rootPane, "EDAD DEBE SER MAYOR A 0 Y MENOR A 150");
                    txt_edadMod.setText("");
                    txt_edadMod.requestFocus();
                }
            }
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "TIPO DE DATO DEBE SER ENTERO");
            txt_edadMod.setText("");
            txt_edadMod.requestFocus();
        }
    }//GEN-LAST:event_txt_edadModActionPerformed

    private void cmb_tipoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoModActionPerformed

    private void chk_atencionModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_atencionModActionPerformed
        if(chk_atencionMod.isSelected())
        {
            txt_cantidadMod.setEnabled(true);
           
        }
        else
        {
            txt_cantidadMod.setEnabled(false);
            txt_cantidadMod.setText("");
            
        }
    }//GEN-LAST:event_chk_atencionModActionPerformed

    private void txt_cantidadModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_cantidadModFocusLost
        try
        {
            if(!txt_cantidadMod.getText().equals(""))
            {
                int edad = Integer.parseInt(txt_edadMod.getText());

                if(edad < 0 )
                {
                    JOptionPane.showMessageDialog(rootPane, "EDAD DEBE SER MAYOR A 0");
                    txt_cantidadMod.setText("");
                    txt_cantidadMod.requestFocus();
                }
            }
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "TIPO DE DATO DEBE SER ENTERO");
            txt_cantidadMod.setText("");
            txt_cantidadMod.requestFocus();
        }
    }//GEN-LAST:event_txt_cantidadModFocusLost

    private void txt_cantidadModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_cantidadModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_cantidadModActionPerformed

    private void chk_duenhoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chk_duenhoModActionPerformed
        if(chk_duenhoMod.isSelected())
        {
            txt_duenhoMod.setEnabled(true);
            
            
            
            
        }
        else
        {
            txt_duenhoMod.setEnabled(false);
            txt_duenhoMod.setText("");
        }
    }//GEN-LAST:event_chk_duenhoModActionPerformed

    private void txt_duenhoModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_duenhoModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duenhoModActionPerformed

    private void txt_duenhoModKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_duenhoModKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_duenhoModKeyReleased

    private void txt_descripcionModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripcionModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripcionModActionPerformed

    private void txt_descripcionModKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_descripcionModKeyReleased
        String textoIngresado = txt_descripcionMod.getText();
        int longitudIngresada = textoIngresado.length();
        
        if(longitudIngresada > 250)
        {
            txt_descripcionMod.setText(textoIngresado.substring(0, 250));
        }
    }//GEN-LAST:event_txt_descripcionModKeyReleased

    private void btn_limpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limpiar1ActionPerformed
        // BOTON LIMPIAR
        
        limpiarVentana();
    }//GEN-LAST:event_btn_limpiar1ActionPerformed

    private void btn_modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarActionPerformed
            Mascota mascota = new Mascota();
            ControladorMascota ctrlMascota = new ControladorMascota();
            boolean validador = false;


            
            String idValidador = txt_idMod.getText();
            
            mascota.setNombreMascota(txt_nombreMod.getText());

            if(!txt_edadMod.getText().equals("")) mascota.setEdad(Integer.parseInt(txt_edadMod.getText()));

           mascota.setTipoMascota((String)cmb_tipoMod.getSelectedItem());

            if(chk_atencionMod.isSelected()){
                mascota.setAtenPrevias(true);
                mascota.setCantAtenPrevias(Integer.parseInt(txt_cantidadMod.getText()));
            }

            if(chk_duenhoMod.isSelected()){
                mascota.setCheckDuenho(true);
                mascota.setNombreDuenho(txt_duenhoMod.getText());
            }

            if(!txt_descripcionMod.getText().equals("")){
                mascota.setDescripcion(txt_descripcionMod.getText());
            }else{
                mascota.setDescripcion("Sin Descripcion");
            }

            validador = ctrlMascota.modificarMascota(mascota, idValidador);



            if(validador)
                {
                    JOptionPane.showMessageDialog(rootPane, "MASCOTA MODIFICADA EXITOSAMENTE");
                }
                else
                {
                    JOptionPane.showMessageDialog(rootPane, "ERROR AL MODIFICAR MASCOTA");
                }

                limpiarVentana();
    }//GEN-LAST:event_btn_modificarActionPerformed

    private void txt_idModFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_idModFocusLost
        try
        {
            if(!txt_idMod.getText().equals(""))
            {
                int edad = Integer.parseInt(txt_idMod.getText());

                if(edad < 0 )
                {
                    JOptionPane.showMessageDialog(rootPane, "IDENTIFICADOR DEBE SER MAYOR A 0");
                    txt_idMod.setText("");
                    txt_idMod.requestFocus();
                }
            }
                        
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(rootPane, "TIPO DE DATO DEBE SER ENTERO");
            txt_idMod.setText("");
            txt_idMod.requestFocus();
        }
    }//GEN-LAST:event_txt_idModFocusLost

    private void txt_idModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idModActionPerformed

    private void pnl_modificarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_pnl_modificarKeyReleased
        
    }//GEN-LAST:event_pnl_modificarKeyReleased

    private void cmb_tipoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoBuscarActionPerformed

    private void btn_modificarPanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_modificarPanelActionPerformed

        int fila = tbl_mascotas.getSelectedRow();

        if(fila >= 0){
            limpiarVentana();
            pnl_listar.setVisible(false);
            pnl_buscar.setVisible(false);
            pnl_almacenar.setVisible(false);
            pnl_modificar.setVisible(true);
            setTitle("MEDIPED - MODIFICAR MASCOTA");
            txt_idMod.setEditable(false);

            txt_idMod.setText(tbl_mascotas.getValueAt(fila,0).toString());
            txt_nombreMod.setText(tbl_mascotas.getValueAt(fila,1).toString());
            txt_edadMod.setText(tbl_mascotas.getValueAt(fila,2).toString());
            cmb_tipoMod.setSelectedItem((String)tbl_mascotas.getValueAt(fila, 3));

            if((boolean)tbl_mascotas.getValueAt(fila, 4)){
                chk_duenhoMod.setSelected(true);
                txt_duenhoMod.setEditable(true);
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "DEBE SELECCIONAR UNA FILA");
        }

    }//GEN-LAST:event_btn_modificarPanelActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
        int columna = 0;
        int fila = tbl_mascotas.getSelectedRow();

        int valorEliminar =
        (int) tbl_mascotas.getModel().getValueAt(fila, columna);

        ControladorMascota ctrlMascota = new ControladorMascota();

        ctrlMascota.mascotaEliminar(valorEliminar);

    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        if(tipoBusqueda == TipoBusqueda.Nombre)
        {
            ArrayList<Mascota> listaMascotas = new ArrayList<>();
            ControladorMascota ctrlMascota = new ControladorMascota();

            //buscar de una caja de  texto
            listaMascotas = ctrlMascota.mascotaBuscarNombre(txt_buscar.getText());

            DefaultTableModel mascotaMostrar =
            (DefaultTableModel)tbl_mascotas.getModel();

            mascotaMostrar.setRowCount(0); //LIMPIA LA TABLA

            for(Mascota x: listaMascotas)
            {
                Object[] objs = {x.getIdMascota(), x.getNombreMascota(), x.getEdad()
                    ,x.getTipoMascota(),x.isCheckDuenho()};

                mascotaMostrar.addRow(objs);
            }
        }else if(tipoBusqueda == TipoBusqueda.Tipo)
        {
            ArrayList<Mascota> listaMascotas = new ArrayList<>();
            ControladorMascota ctrlMascota = new ControladorMascota();

            //buscar de un combox
            listaMascotas = ctrlMascota.mascotaBuscarTipo((String) cmb_tipoBuscar.getSelectedItem());

            DefaultTableModel mascotaMostrar =
            (DefaultTableModel)tbl_mascotas.getModel();

            mascotaMostrar.setRowCount(0); //LIMPIA LA TABLA

            for(Mascota x: listaMascotas)
            {
                Object[] objs = {x.getIdMascota(), x.getNombreMascota(), x.getEdad()
                    ,x.getTipoMascota(),x.isCheckDuenho()};

                mascotaMostrar.addRow(objs);
            }
        }

    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_buscarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_buscarKeyReleased
        String textoIngresado = txt_nombre.getText();
        int longitudIngresada = textoIngresado.length();

        if(longitudIngresada > 50)
        {
            txt_nombre.setText(textoIngresado.substring(0, 50));
        }
    }//GEN-LAST:event_txt_buscarKeyReleased

    private void txt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_buscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_buscarActionPerformed

    private void rbt_tipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_tipoActionPerformed

        if(rbt_tipo.isSelected())
        {
            tipoBusqueda = TipoBusqueda.Tipo;
            cmb_tipoBuscar.setEnabled(true);
            txt_buscar.setEnabled(false);
        }
        else
        {
            cmb_tipoBuscar.setEnabled(false);
        }
    }//GEN-LAST:event_rbt_tipoActionPerformed

    private void rbt_nombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbt_nombreActionPerformed

        if(rbt_nombre.isSelected())
        {
            tipoBusqueda = TipoBusqueda.Nombre;
            cmb_tipoBuscar.setEnabled(false);
            txt_buscar.setEnabled(true);

        }
        else
        {
            txt_buscar.setEnabled(false);
            txt_buscar.setText("");
        }
    }//GEN-LAST:event_rbt_nombreActionPerformed

    //METODO PARA LIMPIAR LA VENTANA COMPLETA
    //SE HACE APARTE PARA QUE EN CASO QUE SE ALMACENE CORRECTAMENTE SE LIMPIE AUTOMATICAMENTE
    private void limpiarVentana()
    {
        
        //LIMPIEZA DE LOS CAMPOS DE TEXTO
        txt_nombre.setText("");
        txt_edad.setText("");
        txt_duenho.setEnabled(false);
        txt_duenho.setText("");
        txt_descripcion.setText("");
        txt_cantidad.setEnabled(false);
        txt_cantidad.setText("");
        
        
        txt_nombreMod.setText("");
        txt_edadMod.setText("");
        txt_duenhoMod.setEnabled(false);
        txt_duenhoMod.setText("");
        txt_descripcionMod.setText("");
        txt_cantidadMod.setEnabled(false);
        txt_cantidadMod.setText("");
        
        
        //LIMPIEZA DE LOS SELECCIONABLES
        cmb_tipo.setSelectedIndex(0);
        cmb_tipoMod.setSelectedIndex(0);
        cmb_tipoBuscar.setSelectedIndex(0);
        
        chk_duenho.setSelected(false);
        chk_duenhoMod.setSelected(false);
        chk_atencion.setSelected(false);
        chk_atencionMod.setSelected(false);
        
        
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }
    
    //METODO QUE VALIDA REGLAS DE NEGOCIO
    private boolean validarReglasNegocio()
    {
        boolean indicador = true;
        
        try{
            
            String opcion = (String)cmb_tipo.getSelectedItem();
            
            if(opcion.equals("-Seleccione-")){
                indicador = false;
                JOptionPane.showMessageDialog(rootPane, "SELECCIONE UN TIPO");
            }
            
            if(txt_nombre.getText().equals("")){
                indicador = false;
                JOptionPane.showMessageDialog(rootPane, "FAVOR INGRESE NOMBRE");
            }
            
            int edad = 0;
            
            if(!txt_edad.getText().equals("")){
                edad = Integer.parseInt(txt_edad.getText());
            }
            
            if(edad < 0 || edad > 150){
                indicador = false;
                
            }
            
            
            
            int cantidad = 0;
            if(!txt_cantidad.getText().equals("")){
                cantidad = Integer.parseInt(txt_cantidad.getText());
            }
            
            if(cantidad < 0){
                indicador = false;
            }
            
            return indicador;
        }catch(Exception ex){
            indicador = false;
            return indicador;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_almacenar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_limpiar;
    private javax.swing.JButton btn_limpiar1;
    private javax.swing.JButton btn_listar;
    private javax.swing.JButton btn_modificar;
    private javax.swing.JButton btn_modificarPanel;
    private javax.swing.ButtonGroup btt_buscar;
    private javax.swing.JCheckBox chk_atencion;
    private javax.swing.JCheckBox chk_atencionMod;
    private javax.swing.JCheckBox chk_duenho;
    private javax.swing.JCheckBox chk_duenhoMod;
    private javax.swing.JComboBox<String> cmb_tipo;
    private javax.swing.JComboBox<String> cmb_tipoBuscar;
    private javax.swing.JComboBox<String> cmb_tipoMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JLabel lbl_1;
    private javax.swing.JLabel lbl_10;
    private javax.swing.JLabel lbl_11;
    private javax.swing.JLabel lbl_12;
    private javax.swing.JLabel lbl_13;
    private javax.swing.JLabel lbl_14;
    private javax.swing.JLabel lbl_15;
    private javax.swing.JLabel lbl_17;
    private javax.swing.JLabel lbl_18;
    private javax.swing.JLabel lbl_2;
    private javax.swing.JLabel lbl_3;
    private javax.swing.JLabel lbl_4;
    private javax.swing.JLabel lbl_5;
    private javax.swing.JLabel lbl_6;
    private javax.swing.JLabel lbl_7;
    private javax.swing.JLabel lbl_8;
    private javax.swing.JLabel lbl_9;
    private javax.swing.JMenu men_opcion;
    private javax.swing.JMenuItem mi_almacenar;
    private javax.swing.JMenuItem mi_buscar;
    private javax.swing.JMenuItem mi_listar;
    private javax.swing.JMenuBar mnb_1;
    private javax.swing.JPanel pnl_almacenar;
    private javax.swing.JPanel pnl_buscar;
    private javax.swing.JPanel pnl_listar;
    private javax.swing.JPanel pnl_modificar;
    private javax.swing.JRadioButton rbt_nombre;
    private javax.swing.JRadioButton rbt_tipo;
    private javax.swing.JScrollPane tbl_lista;
    private javax.swing.JScrollPane tbl_lista1;
    private javax.swing.JTable tbl_listamascota;
    private javax.swing.JTable tbl_mascotas;
    private javax.swing.JTextField txt_buscar;
    private javax.swing.JTextField txt_cantidad;
    private javax.swing.JTextField txt_cantidadMod;
    private javax.swing.JTextField txt_descripcion;
    private javax.swing.JTextField txt_descripcionMod;
    private javax.swing.JTextField txt_duenho;
    private javax.swing.JTextField txt_duenhoMod;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextField txt_edadMod;
    private javax.swing.JTextField txt_idMod;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_nombreMod;
    // End of variables declaration//GEN-END:variables
}
